### ISSUE TITLE
Not working on Unbuntu

### ISSUE THREAD

**Issue by AsixJin** [pawbyte/Game-Pencil-Engine#19] opened 2018-02-27 05:38 UTC
I'm trying to get this working on Unbuntu and I've installed libsdl2, but when I try to run it I get the following error:

```
./Game_Pencil_Engine_IDE 
./Game_Pencil_Engine_IDE: error while loading shared libraries: libSDL2_image-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by theweirdn8** [comment] 2018-02-27 14:45
Please install SDL2, SDL2_image, SDL2_mixer and SDL2_ttf

**Comment by AsixJin** [comment] 2018-02-27 16:10
@clee231 @theweirdn8 

Thank you that fixed it right up! Can't wait to explore this IDE!

**Comment by clee231** [comment] 2018-02-27 17:18
Glad to see this is working for you now! :smile: 
Closing the issue for now.  If you run into any other issues, feel free to make another issue or append to this one if the issue is related.

**Closed by clee231** 2018-02-27 17:18 UTC

**Comment by theweirdn8** [comment] 2018-02-27 18:46
@AsixJin yea I will say just check out things, the new version that will have a ton of new cool things is almost here!
